### ISSUE TITLE
Mark package as `Abandoned` on packagist

### ISSUE THREAD

**Issue by mdrost** [container-interop/container-interop#94] opened 2017-05-02 21:00 UTC
Marking package as `Abandoned` on packagist should prevent new users from relying on this package and should accelerate migrating to PSR-11 when users start see warnings on composer update.

**Comment by Ocramius** [comment] 2017-05-08 12:51
Unsure if this should already happen. Are we going to keep experimenting with further interfaces in here, @moufmouf @mnapoli?

**Comment by mnapoli** [comment] 2017-05-08 16:17
In this package I don't think so (if there are new interfaces it might be better to make a new repository).

**Comment by Potherca** [comment] 2017-05-08 16:40
To put in my two penny worth:

- I think marking this package as abandoned (in favour of PSR-11) is a sensible move.
- I agree that any further experiments would be better suited as a separate repository.

**Comment by moufmouf** [comment] 2017-05-15 09:24
I agree with @mnapoli . New interfaces will likely be part of a new repository (like service-providers for instance).

I have no strong objections to mark this package as abandoned. Yet, it is used by quite a number of projects (like Zend Service-manager) and viewing these deprecation notices might scare users of those projects (they don't necessarily understand what's going on behind the scene and whether they should worry or not).

Maybe we should ping @weierophinney before making this move?

**Comment by Ocramius** [comment] 2017-05-15 09:33
Meanwhile, given the previous comments, I agree that abandoning the package
is a sensible choice.

**Comment by mdrost** [comment] 2017-07-18 16:29
So what's the decision?

**Comment by mindplay-dk** [comment] 2017-12-05 10:45
> Yet, it is used by quite a number of projects (like Zend Service-manager) and viewing these deprecation notices might scare users of those projects (they don't necessarily understand what's going on behind the scene and whether they should worry or not).

This concern is similar to what I noted in #96.

I'm afraid the mistake here was to attempt to create backwards compatibility with the legacy package in the first place - it has caused all manner of problems, for one because implementing the same interface twice triggers a PHP error. A clean break would have been much simpler.

What's done is done, but as things stand, I'm now in favor of marking the package as abandoned.

Yes, the deprecation notices will scare some users - this is probably a good thing, as the users will likely alert the maintainers, which will encourage them to break from the legacy package.

In addition to marking the package as abandoned, I'd suggest we use a `post-package-install` and `post-package-update` in `composer.json` to further explain the situation. For example, encourage users to run `composer why container-interop/container-interop` and notify maintainers or send PRs.

Fully adopting `psr/container` is only possible with a breaking change - we need to encourage everyone to make that breaking change and drive everyone away from the legacy package as quickly as possible. It's been a year. No one should be using the legacy package anymore.

I'd suggest to anyone maintaining a DI container that, when you make this breaking change, you also flag the legacy package using `conflicts` in `composer.json`, as basically any DI container that exclusively uses the final package will fail when used in combination with anything that still depends on the legacy interfaces.

I *was* going to copy the legacy package into my DI container and use `replace` in `composer.json` to suppress the installation of the legacy package (and any future deprecation notice) while maintaining backwards compatibility. I strongly discourage everyone from doing that - the situation is ugly, and having to publish a major release because of this is frustrating; passing on the burden, forcing every dependent package to publish a major release, is ugly, but seems like a necessary evil now that the damage is done.

**Comment by shochdoerfer** [comment] 2017-12-05 16:17
The latest container-interop package extends the PSR-11 interfaces. Shouldn't that fix the issue?

**Comment by mindplay-dk** [comment] 2017-12-06 14:16
> The latest container-interop package extends the PSR-11 interfaces. Shouldn't that fix the issue?

Yes, the legacy package is *forward* compatible - but the final interfaces aren't *backwards* compatible.

If you want to depend on the legacy package forever, you're fine.

If the legacy package gets marked as abandoned, you won't want to depend on the legacy package anymore, because warnings will be issued to Composer users - at this point, because the new interfaces aren't backwards compatible, your only choice is a BC break.

I currently depend on both, mainly to signal that I've considered the final package - not because I actually depend on the final interfaces; the only way I can implement the final interfaces, is by breaking backwards compatibility with the legacy package, so that requires a major release.

To make things more confusing, whether or not you have this problem, depends on whether the issue is covariance or contravariance. That is, if your package is a DI container, you're implementing the interface - you can't implement the new one, you have to keep implementing the old one, or forego BC. Conversely, if your package is something that depends on a DI container (uses it to type-hint a parameter) you *can* type-hint using either the new or old interface.

It's a very odd situation :-/

**Comment by weierophinney** [comment] 2017-12-06 15:55
> I currently depend on both, mainly to signal that I've considered the final package - not because I actually depend on the final interfaces; the only way I can implement the final interfaces, is by breaking backwards compatibility with the legacy package, so that requires a major release.

That was the intent behind the last release of this package: making _implementations_ forwards compatible with PSR-11, without requiring an immediate change and major version bump.

**Consumers can depend on PSR-11 interfaces, as classes implementing the latest version of container-interop also implement PSR-11.** This is not a trivial thing to say; it's actually very powerful, as it meant that for a large number of developers, they were able to immediately start typehinting against PSR-11 without having to upgrade the DiC they were using.

Packages that are implementing container-interop will of course need to bump major versions once they directly implement the PSR-11 interface. But by having this package in place, they are able to delay that change, which would impact their own consumers.

I see this as a pretty big win for the ecosystem, honestly.

**Comment by mindplay-dk** [comment] 2017-12-07 09:08
> it meant that for a large number of developers, they were able to immediately start typehinting against PSR-11 without having to upgrade the DiC they were using.

Here's where we disagree.

We gave them an excuse not to upgrade - encouraged them not to, even. In doing so, it would be fair to also expect us to provide backwards compatibility, which we're now obliged to do. Even major DI containers like php-di have not upgraded, likely for the same reason.

We created this situation just so that nobody would have to spend two minutes doing a "search and replace in files" to switch to the final package and official interfaces.

> I see this as a pretty big win for the ecosystem, honestly.

IMO, we created more work than we saved anyone.

What I'd like to encourage for future PSRs, is instead we *start* with the correct namespace, even if the package name is wrong - version the package as needed until stable, then mark as abandoned and mark the final package as `conflicts` in `composer.json` with the legacy package, *forcing* everyone to update `composer.json`, but saving everyone from any concerns or reservations about switching from (last stable) legacy package to the official one, and creating *zero* code changes for the switch to the final package.

Note that I agreed with the chosen approach at the time, and I'm sure you meant well, as did I, but I now strongly feel that we made a mistake. It's been a year, and major DI containers *still* implement the legacy interfaces - I reckon that spells failure.

**Comment by mdrost** [comment] 2017-12-07 12:39
>It's been a year, and major DI containers still implement the legacy interfaces

So let them die :)

**Comment by shochdoerfer** [comment] 2017-12-07 18:31
I don't get the problem. Isn't it up the package maintainer to decide if and when to migrate to psr/container?

**Comment by mnapoli** [comment] 2017-12-07 18:36
> Even major DI containers like php-di have not upgraded, likely for the same reason.

In a minor version I required latest version of this package, so PHP-DI can be used anywhere PSR-11 is required. In v6 (coming soon) I'll drop container-interop completely to support PSR-11 only.

In this specific context: what is the problem?

To be honest I have trouble understanding what we are arguing about ;) I haven't heard about problems with that approach from users, and as a maintainer I was very happy with how easy it was.

**Comment by mindplay-dk** [comment] 2017-12-09 14:22
> In v6 (coming soon) I'll drop container-interop completely to support PSR-11 only.

Maybe you had a major release coming up anyway?

I don't have any major release planned - being forced into a major release is part of what bothers me, and the other problem is, even with a major release, users will need to learn the painful way that the package is now incompatible with the legacy package, since there's nothing preventing them from trying to use it just because my package doesn't depend on or support it anymore, unless I also flag the legacy package using `conflicts`, which would seem wrong, given that it's not *my* package that conflicts with the legacy package, but the final PSR-11 package.

Either way, sounds like nobody else is bothered by any of this, so maybe it's just me.

**Comment by stof** [comment] 2019-11-14 15:15
> What I'd like to encourage for future PSRs, is instead we _start_ with the correct namespace, even if the package name is wrong - version the package as needed until stable, then mark as abandoned and mark the final package as `conflicts` in `composer.json` with the legacy package, _forcing_ everyone to update `composer.json`, but saving everyone from any concerns or reservations about switching from (last stable) legacy package to the official one, and creating _zero_ code changes for the switch to the final package.

that's even worse during the experimentation phase: if you start with the final interface name but not the final interface signature, some code might typehint the interface expecting the experimental signature, and then fail if a project satisfies the typehint using the official PSR.

**Comment by mindplay-dk** [comment] 2019-11-15 10:53
> if you start with the final interface name but not the final interface signature, some code might typehint the interface expecting the experimental signature, and then fail if a project satisfies the typehint using the official PSR.

Hence `conflicts`. 🤷‍♂️

Also, if you're using an experimental package before it's release, expect things to break - it's natural.

**Comment by stof** [comment] 2019-11-15 11:58
Well, the conflict will work only if the package containing the typehint has a requirement on the interface package. But that might not be the case if it was an optional integration.

**Comment by Potherca** [comment] 2019-11-16 18:42
Although discussions are always fun I don't think they are moving the issue at hand in any useful direction. Especially since this thread has been dormant for almost 2 years.

Can we get a quick vote from all of those involved in this thread? That should make it clear if there is actually any base for further discussion.



So...

- [x] @mdrost (Original Poster)
- [x] @mindplay-dk (Contributor)
- [x] @mnapoli  (Member)
- [x] @moufmouf (Contributor)
- [x] @Ocramius (Member)
- [x] @shochdoerfer (Contributor)
- [ ] @stof  (Commenter)
- [x] @weierophinney (Commenter)

could you comment if you are for or against marking `container-interop/container-interop` as "Abandoned" on packagist?

**Comment by Ocramius** [comment] 2019-11-16 18:56
Package can be abandoned on packagist 👍

**Comment by mnapoli** [comment] 2019-11-16 18:57
👍  (voted on the checklist)

**Comment by shochdoerfer** [comment] 2019-11-17 08:37
Package can be abandoned :+1:

**Comment by shochdoerfer** [comment] 2019-11-17 08:37
Package can be abandoned :+1:

**Comment by mindplay-dk** [comment] 2019-11-17 08:54
Abandon 👍

**Comment by weierophinney** [comment] 2019-11-18 15:12
:+1: to abandon!

**Comment by Potherca** [comment] 2019-11-18 15:30
We are only awaiting the input of 2 more people (one contributor, one commenter)

As everybody else has already voted _in favour_, I would suggest further discussion would _not_ be needed and the package can be marked as abandoned on packagist. 

@mnapoli Would you like to take the honours?

**Comment by mnapoli** [comment] 2019-11-18 15:33
Let me ping @moufmouf quickly, we started this project together :)

**Comment by moufmouf** [comment] 2019-11-19 14:20
:+1: to abandon, let's do this!

**Comment by moufmouf** [comment] 2019-11-19 14:21
... aaaaand it's done: https://packagist.org/packages/container-interop/container-interop
:)

**Closed as completed by moufmouf** 2019-11-19 14:21 UTC
