### ISSUE TITLE
ContainerAwareInterface ?

### ISSUE THREAD

**Issue by neiluJ** [container-interop/container-interop#50] opened 2015-11-03 14:17 UTC
Hello ! Do you think a ```ContainerAwareInterface``` would fit in container-interop? I think it could be useful for frameworks and di-oriented libraries to have a standard way to tell their objects are using the Container, but I don't know if this fits in here so I'm just asking the question.

Something like this:
``` php
namespace Interop\Container;

/**
 * Describes an object that is "aware" of the Dependency Injection Container
 */
interface ContainerAwareInterface
{
    /**
     * Defines the Dependency Injection Container
     *
     * @param ContainerInterface $container The DI Container
     *
     * @return void
     */
    public function setContainer(ContainerInterface $container);

    /**
     * Returns the Dependency Injection Container
     *
     * @return ContainerInterface
     */
    public function getContainer();
}
```

Cheers

**Comment by Ocramius** [comment] 2015-11-03 22:14
This is generally perceived as anti-pattern and very dependency-injection unfriendly ("ContainerAware is the new Singleton", from what I heard on the internets).

While the `ContainerInterface` is indeed a very controversial interface, this one would be plain bad/dangerous.

**Comment by Ocramius** [comment] 2015-11-03 22:15
I'm closing: if anybody feels like this needs more discussion, feel free to stone me on the twitters ([relevant](https://www.youtube.com/watch?v=SYkbqzWVHZI))

**Closed by Ocramius** 2015-11-03 22:15 UTC
Labels: enhancement, question

**Comment by neiluJ** [comment] 2015-11-03 23:10
Didn't know about this! It's a very interesting point of view and I must agree that it could be considered as an anti-pattern... Just for the debate I'd say that the real anti-pattern would be having a *Service* being "Container Aware" (like in [this example](https://qafoo.com/blog/057_containeraware_considered_harmful.html)) but IMHO it doesn't seem so bad for a *Controller* or a *Kernel* that could handle() 

Thanks for answers :beer:

**Comment by shochdoerfer** [comment] 2015-11-04 14:33
@neiluJ the problem is if you allow people to use it, people will use it and not for the good. That's the main problem with this interface ;)

**Comment by neiluJ** [comment] 2015-11-05 13:35
@shochdoerfer one may probably kill someone (or himself) with a swiss army kniffe, yet it's still a very useful tool when used properly :) But I agree that this is probably not a good comparision when trying to define a standard...

**Comment by njasm** [comment] 2015-11-05 17:22
With great power, comes with great responsability... someone said something like that i believe... :)

**Comment by moufmouf** [comment] 2015-11-05 18:07
Yeah, also using the ContainerInterface as a service locator (which is what the `ContainerAwareInterface` advocates) is what is frightening a lot of people and slowing the adoption of container-interop as PSR-11 (you can have a look at the PHP-FIG mailing list, there has already been a lot of talk about it).

This is why PSR-11 will probably have a "warning text" about not using the container as a service locator (proposed text is here: https://github.com/container-interop/fig-standards/pull/6/files )
